version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ${APP_ENV}/Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"
    networks:
      - app-network

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
